from config import *

BACKBONE = "simple"
DP = 0.0
NUM_ROUTING = 1
SENTENCE_LENGTH = EMBEDDING_SIZE
NUM_CODEBOOK = 8
NUM_CODEWORD = None
IN_CHANNELS = 1
NUM_ITERATIONS = 3
NUM_REPEAT = None
OUT_CHANNELS = 128
SEQUENTIAL_ROUTING = True
EMBEDDING_TYPE = "cwc"
NUM_REPEAT = None
LOSS_TYPE = "mf"